
export const listData = [
    {
        id: 1,
        name: "Áo thun",
        type: "1",
        price: 15000,
        description: "Đây là áo thun",
        amount: "20",
        image: "https://vn-test-11.slatic.net/p/b982fe3c7517d19571e1f0a6f24679f7.jpg",
    },
    {
        id: 2,
        name: "Áo khoác gió",
        type: "1",
        price: 10000,
        description: "Đây là áo thun B",
        amount: "10",
        image: "https://vn-test-11.slatic.net/p/b982fe3c7517d19571e1f0a6f24679f7.jpg",
    },
    {
        id: 3,
        name: "Áo nỉ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun C",
        amount: "5",
        image: "https://vn-test-11.slatic.net/p/b982fe3c7517d19571e1f0a6f24679f7.jpg",
    },
    {
        id: 4,
        name: "Quần âu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 5,
        name: "Áo hoodie Mỹ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 6,
        name: "Áo LV",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 7,
        name: "Quần bò da",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 8,
        name: "Quần jogger hàng hiệu",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 9,
        name: "Áo thu đông",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 10,
        name: "Quần đồng phục học sinh",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 11,
        name: "Quần short",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 12,
        name: "Áo ba lỗ",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
    {
        id: 13,
        name: "Quần sịp",
        type: "1",
        price: 10000,
        description: "Đây là áo thun D",
        amount: "30",
        image: null,
    },
];